### ISSUE TITLE
Unbound `oz` in Conv3dDynamicSamePadding

### ISSUE THREAD

**Issue by markussteindl** [shijianjian/EfficientNet-PyTorch-3D#18]
Do you mean `iz / sz` instead of `iz / oz`?

https://github.com/shijianjian/EfficientNet-PyTorch-3D/blob/3e79bcd06216b2e831bf3300fff9636cce2cd0d1/efficientnet_pytorch_3d/utils.py#L114

**Comment by shijianjian** [comment]
shall be fixed
