### ISSUE TITLE
How to train from scratch used myself dataset?

### ISSUE THREAD

**Issue by BigBug-NJU** [shijianjian/EfficientNet-PyTorch-3D#5]
It's difficult for me to train the net using my 3d dataset, for example, how to load data、preprocess.
Can anyone share train script? 
Thanks all.

**Comment by dscarmo** [comment]
Have a look at PyTorch tutorials, you will just need to adapt to 3D as input. https://pytorch.org/tutorials/

**Comment by shijianjian** [comment]
Closed since it is not related to the repo.
