### ISSUE TITLE
UnboundLocalError: local variable 'oz' referenced before assignment

### ISSUE THREAD

**Issue by DanielDauner** [shijianjian/EfficientNet-PyTorch-3D#7]
Hi,

I'm not 100% sure but I think I found a little Issue. In line 114 of utils.py the variable 'oz' has to be changed into the variable 'sz', otherwise I get an error.

https://github.com/shijianjian/EfficientNet-PyTorch-3D/blob/c33efbba18970cb45f481601494379ff91d4b850/efficientnet_pytorch_3d/utils.py#L114

**Comment by shijianjian** [comment]
@DanielDauner, sorry for the late response. Do mind throwing a PR?
